/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Core.Drawer;
import Core.EEGFile;
import Core.EEGSignal;
import Core.Predictor;
import Core.Report;
import Core.ReportWriter;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Sahan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        setToolIcons();
        saveResultButton.setEnabled(false);
        predictASDButton.setEnabled(false);
        System.out.println(EEGFile.getInstance().getFilePath());
        setReportDate(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluateDataRButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PredictPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        eegImportOuterPanel = new javax.swing.JPanel();
        importEEGHeadingLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        browseBtn = new javax.swing.JButton();
        browseTxt = new javax.swing.JTextField();
        predictASDButton = new javax.swing.JButton();
        pDetailOuterPanel = new javax.swing.JPanel();
        pDetaiHeadinglLabel = new javax.swing.JLabel();
        pDetailInnerLabel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        saveResultButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        predictionPanel = new javax.swing.JPanel();
        mainPreditionResultPanel = new javax.swing.JPanel();
        resultHeaderLabel = new javax.swing.JLabel();
        resultSeperator = new javax.swing.JSeparator();
        nameResultLabel = new javax.swing.JLabel();
        ageResultLabel = new javax.swing.JLabel();
        genderResultLabel = new javax.swing.JLabel();
        dateResultLabel = new javax.swing.JLabel();
        resultPanel = new javax.swing.JPanel();
        descriptionText = new javax.swing.JLabel();
        resultText = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        nameResultText = new javax.swing.JLabel();
        ageResultText = new javax.swing.JLabel();
        dateResultText = new javax.swing.JLabel();
        genderResultText = new javax.swing.JLabel();
        eegSignalDetailsLabel = new javax.swing.JLabel();
        noOfChannelsDetailsLabel = new javax.swing.JLabel();
        durationDetailsLabel = new javax.swing.JLabel();
        recordedDateDetailsLabel = new javax.swing.JLabel();
        noOfChannelsDetailsText = new javax.swing.JLabel();
        durationDetailsText = new javax.swing.JLabel();
        recordedDateDetailsText = new javax.swing.JLabel();
        channelNamesDetailsLabel = new javax.swing.JLabel();
        channelNamesDetailsText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        asdResultLabel = new javax.swing.JLabel();
        VisualizePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        visualizeLabel = new javax.swing.JLabel();
        visualizeNameLabel = new javax.swing.JLabel();
        changeViewComboBox = new javax.swing.JComboBox<>();
        HelpPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ASDGenus | Tool for Lives");
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(1380, 740));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabSelectChanged(evt);
            }
        });

        PredictPanel.setFocusable(false);
        PredictPanel.setRequestFocusEnabled(false);
        PredictPanel.setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(214, 217, 223));

        imagePanel.setBackground(new java.awt.Color(255, 255, 255));
        imagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagePanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        importEEGHeadingLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        importEEGHeadingLabel.setText("Import EEG File");

        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        browseBtn.setText("Choose");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        browseTxt.setText("Choose a file");
        browseTxt.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browseTxt)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(browseBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(browseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout eegImportOuterPanelLayout = new javax.swing.GroupLayout(eegImportOuterPanel);
        eegImportOuterPanel.setLayout(eegImportOuterPanelLayout);
        eegImportOuterPanelLayout.setHorizontalGroup(
            eegImportOuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eegImportOuterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eegImportOuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(eegImportOuterPanelLayout.createSequentialGroup()
                        .addComponent(importEEGHeadingLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        eegImportOuterPanelLayout.setVerticalGroup(
            eegImportOuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eegImportOuterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(importEEGHeadingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        predictASDButton.setText("Predict ASD");
        predictASDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predictASDButtonActionPerformed(evt);
            }
        });

        pDetaiHeadinglLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pDetaiHeadinglLabel.setText("Personal Details");

        pDetailInnerLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        nameLabel.setText("Name");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTextEnterKeyPressed(evt);
            }
        });

        ageLabel.setText("Age");

        ageText.setToolTipText("");
        ageText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageTextEnterKeyPressed(evt);
            }
        });

        genderLabel.setText("Gender");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Male", "Female" }));
        genderComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                genderJBoxItemChanged(evt);
            }
        });

        javax.swing.GroupLayout pDetailInnerLabelLayout = new javax.swing.GroupLayout(pDetailInnerLabel);
        pDetailInnerLabel.setLayout(pDetailInnerLabelLayout);
        pDetailInnerLabelLayout.setHorizontalGroup(
            pDetailInnerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailInnerLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDetailInnerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pDetailInnerLabelLayout.createSequentialGroup()
                        .addGroup(pDetailInnerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderLabel)
                            .addComponent(ageLabel))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pDetailInnerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDetailInnerLabelLayout.createSequentialGroup()
                        .addComponent(ageText)
                        .addGap(40, 40, 40))
                    .addGroup(pDetailInnerLabelLayout.createSequentialGroup()
                        .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDetailInnerLabelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pDetailInnerLabelLayout.setVerticalGroup(
            pDetailInnerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailInnerLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDetailInnerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDetailInnerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDetailInnerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pDetailOuterPanelLayout = new javax.swing.GroupLayout(pDetailOuterPanel);
        pDetailOuterPanel.setLayout(pDetailOuterPanelLayout);
        pDetailOuterPanelLayout.setHorizontalGroup(
            pDetailOuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailOuterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDetailOuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pDetaiHeadinglLabel)
                    .addComponent(pDetailInnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        pDetailOuterPanelLayout.setVerticalGroup(
            pDetailOuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailOuterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pDetaiHeadinglLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pDetailInnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveResultButton.setText("Save Results");
        saveResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveResultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(eegImportOuterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveResultButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(predictASDButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pDetailOuterPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pDetailOuterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(eegImportOuterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(predictASDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(saveResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        predictionPanel.setRequestFocusEnabled(false);
        predictionPanel.setVerifyInputWhenFocusTarget(false);

        mainPreditionResultPanel.setBackground(new java.awt.Color(250, 250, 250));
        mainPreditionResultPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        mainPreditionResultPanel.setAutoscrolls(true);

        resultHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        resultHeaderLabel.setText("Autism Spectrum Disorder Prediction Result");
        resultHeaderLabel.setFocusable(false);

        nameResultLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameResultLabel.setText("Name :");

        ageResultLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ageResultLabel.setText("Age : ");

        genderResultLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderResultLabel.setText("Gender : ");

        dateResultLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateResultLabel.setText("Date :");

        resultPanel.setBackground(new java.awt.Color(102, 204, 225));

        descriptionText.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        descriptionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionText.setText("--");

        resultText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resultText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultText.setText("--");
        resultText.setAutoscrolls(true);
        resultText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        resultLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultLabel.setText("--------------------------------------- Result ---------------------------------------");

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descriptionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(resultText, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(resultLabel)
                .addGap(18, 18, 18)
                .addComponent(resultText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionText)
                .addContainerGap())
        );

        nameResultText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ageResultText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        dateResultText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        genderResultText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        eegSignalDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eegSignalDetailsLabel.setText("Additional Details about the EEG signal :");

        noOfChannelsDetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        noOfChannelsDetailsLabel.setText("Number of channels -");

        durationDetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        durationDetailsLabel.setText("Duration -");

        recordedDateDetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        recordedDateDetailsLabel.setText("Recorded date -");

        noOfChannelsDetailsText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        durationDetailsText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        recordedDateDetailsText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        channelNamesDetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        channelNamesDetailsLabel.setText("Channel names -");

        channelNamesDetailsText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel1.setText("The above report is generated based on the data you provided by choosing a .vhdr data file for the ASDGenus to predict ASD for the specific pateint...");

        javax.swing.GroupLayout mainPreditionResultPanelLayout = new javax.swing.GroupLayout(mainPreditionResultPanel);
        mainPreditionResultPanel.setLayout(mainPreditionResultPanelLayout);
        mainPreditionResultPanelLayout.setHorizontalGroup(
            mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(resultHeaderLabel))
                    .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(channelNamesDetailsLabel)
                        .addGap(10, 10, 10)
                        .addComponent(channelNamesDetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(durationDetailsLabel)
                        .addGap(6, 6, 6)
                        .addComponent(durationDetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(recordedDateDetailsLabel)
                        .addGap(10, 10, 10)
                        .addComponent(recordedDateDetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(eegSignalDetailsLabel))
                    .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(noOfChannelsDetailsLabel)
                        .addGap(6, 6, 6)
                        .addComponent(noOfChannelsDetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                                .addComponent(ageResultLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                                .addComponent(nameResultLabel)
                                .addGap(10, 10, 10)
                                .addComponent(nameResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(335, 335, 335)
                        .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                                .addComponent(dateResultLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dateResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                                .addComponent(genderResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPreditionResultPanelLayout.setVerticalGroup(
            mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPreditionResultPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(resultHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameResultLabel)
                        .addComponent(genderResultLabel))
                    .addComponent(nameResultText)
                    .addComponent(genderResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ageResultText)
                        .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageResultLabel)
                            .addComponent(dateResultLabel)))
                    .addComponent(dateResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(eegSignalDetailsLabel)
                .addGap(28, 28, 28)
                .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noOfChannelsDetailsLabel)
                    .addComponent(noOfChannelsDetailsText))
                .addGap(18, 18, 18)
                .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(channelNamesDetailsLabel)
                    .addComponent(channelNamesDetailsText))
                .addGap(18, 18, 18)
                .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durationDetailsLabel)
                    .addComponent(durationDetailsText))
                .addGap(18, 18, 18)
                .addGroup(mainPreditionResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recordedDateDetailsLabel)
                    .addComponent(recordedDateDetailsText))
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        asdResultLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        asdResultLabel.setText("ASD Prediction Result");

        javax.swing.GroupLayout predictionPanelLayout = new javax.swing.GroupLayout(predictionPanel);
        predictionPanel.setLayout(predictionPanelLayout);
        predictionPanelLayout.setHorizontalGroup(
            predictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(predictionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(predictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(predictionPanelLayout.createSequentialGroup()
                        .addComponent(asdResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mainPreditionResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1091, Short.MAX_VALUE))
                .addContainerGap())
        );
        predictionPanelLayout.setVerticalGroup(
            predictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(predictionPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(asdResultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPreditionResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PredictPanelLayout = new javax.swing.GroupLayout(PredictPanel);
        PredictPanel.setLayout(PredictPanelLayout);
        PredictPanelLayout.setHorizontalGroup(
            PredictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PredictPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(predictionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        PredictPanelLayout.setVerticalGroup(
            PredictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PredictPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PredictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(predictionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", PredictPanel);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        visualizeLabel.setBackground(new java.awt.Color(255, 255, 255));
        visualizeLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visualizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visualizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        visualizeNameLabel.setText("Change View :");

        changeViewComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Locations", "EEG Signal" }));
        changeViewComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                changeViewCBoxItemChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(visualizeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeViewComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1214, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visualizeNameLabel)
                    .addComponent(changeViewComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VisualizePanelLayout = new javax.swing.GroupLayout(VisualizePanel);
        VisualizePanel.setLayout(VisualizePanelLayout);
        VisualizePanelLayout.setHorizontalGroup(
            VisualizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VisualizePanelLayout.setVerticalGroup(
            VisualizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visualize", VisualizePanel);

        javax.swing.GroupLayout HelpPanelLayout = new javax.swing.GroupLayout(HelpPanel);
        HelpPanel.setLayout(HelpPanelLayout);
        HelpPanelLayout.setHorizontalGroup(
            HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1445, Short.MAX_VALUE)
        );
        HelpPanelLayout.setVerticalGroup(
            HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Help", HelpPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabSelectChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabSelectChanged
        if(jTabbedPane1.getSelectedIndex()==1){ // Index of the Visualize tab
            changeViewComboBox.setSelectedIndex(0);
            if(!EEGFile.getInstance().getFilePath().isEmpty()){
                ImageIcon imgIcon = new ImageIcon(Drawer.getInstance().getEEGHeadLocationImage());
                if(imgIcon != null){
                    visualizeLabel.setIcon(imgIcon);
                    visualizeLabel.setHorizontalAlignment(JLabel.CENTER);
                    visualizeLabel.setVerticalAlignment(JLabel.CENTER);
                }
            } else{
                JOptionPane.showMessageDialog(VisualizePanel, "Choose a file to plot first!");
                jTabbedPane1.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_tabSelectChanged

    private void saveResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveResultButtonActionPerformed
        if(nameResultText.getText().trim() == "" || nameResultText.getText().trim() == null){
            JOptionPane.showMessageDialog(PredictPanel, "Name is essential for saving data!");
        }else{
            EEGSignal eegSignal = new EEGSignal(noOfChannelsDetailsText.getText().trim(), durationDetailsText.getText().trim(),
                channelNamesDetailsText.getText().trim(), recordedDateDetailsText.getText().trim());
            Report report = new Report(nameResultText.getText().trim(), ageResultText.getText().trim(),
                genderResultText.getText().trim(), dateResultText.getText().trim(),
                resultText.getText().trim(), descriptionText.getText().trim(), eegSignal);
            new ReportWriter().saveReport(report, eegSignal);
            JOptionPane.showMessageDialog(PredictPanel, "Result saved successfully!");
        }
    }//GEN-LAST:event_saveResultButtonActionPerformed

    private void genderJBoxItemChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_genderJBoxItemChanged
        if (evt.getItem().toString() != "Select One"){
            genderResultText.setText(evt.getItem().toString());
        }else{
            genderResultText.setText("");
        }
        setReportDate(false);
    }//GEN-LAST:event_genderJBoxItemChanged

    /**
     * put age in the result after enter key pressed
     * @param evt 
     */
    private void ageTextEnterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextEnterKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!ageText.getText().trim().isEmpty())
            ageResultText.setText(ageText.getText().trim() + " years");
        }
        setReportDate(false);
    }//GEN-LAST:event_ageTextEnterKeyPressed

    /**
     * put name in the result after enter key pressed
     * @param evt 
     */
    private void nameTextEnterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextEnterKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            nameResultText.setText(nameText.getText().trim());
        }
        setReportDate(false);
    }//GEN-LAST:event_nameTextEnterKeyPressed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void predictASDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predictASDButtonActionPerformed
        // Set name, age, and gender on report
        nameResultText.setText(nameText.getText().trim());
        if(!ageText.getText().trim().isEmpty())
        ageResultText.setText(ageText.getText().trim() + " years");
        String gender = genderComboBox.getSelectedItem().toString();
        if (gender != "Select One"){
            genderResultText.setText(gender);
        }else{
            genderResultText.setText("");
        }

        if(!EEGFile.getInstance().getFilePath().isEmpty()){
            ArrayList<String> prediction = Predictor.getInstance().predictASD(EEGFile.getInstance().getFilePath());
            setReportDate(true);
            resultText.setText(prediction.get(0));
            descriptionText.setText(prediction.get(1));
            noOfChannelsDetailsText.setText(prediction.get(2));
            channelNamesDetailsText.setText(prediction.get(3));
            durationDetailsText.setText(prediction.get(4));
            recordedDateDetailsText.setText(prediction.get(5));
            saveResultButton.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(PredictPanel, "Choose a file first, before predicting");
        }
    }//GEN-LAST:event_predictASDButtonActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose File");
        FileNameExtensionFilter vhdrFilter = new FileNameExtensionFilter("vhdr files (*.vhdr)", "vhdr");
        fileChooser.setFileFilter(vhdrFilter);
        int response = fileChooser.showOpenDialog(eegImportOuterPanel);
        if (response == JFileChooser.APPROVE_OPTION){
            browseTxt.setText(fileChooser.getSelectedFile().getName());
            EEGFile.getInstance().setFilePath(fileChooser.getSelectedFile().toString());
            EEGFile.getInstance().setFileName(fileChooser.getSelectedFile().getName());
            predictASDButton.setEnabled(true);
        }
    }//GEN-LAST:event_browseBtnActionPerformed

    private void changeViewCBoxItemChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_changeViewCBoxItemChanged
        ImageIcon imgIcon;
        if (evt.getItem().toString() == "Locations"){
            imgIcon = new ImageIcon(Drawer.getInstance().getEEGHeadLocationImage());
            if(imgIcon != null){
                visualizeLabel.setIcon(imgIcon);
                visualizeLabel.setHorizontalAlignment(JLabel.CENTER);
                visualizeLabel.setVerticalAlignment(JLabel.CENTER);
            }
        }else if(evt.getItem().toString() == "EEG Signal"){
            imgIcon = getFitSizeImage(Drawer.getInstance().getEEGSignalImage());
            if(imgIcon != null){
                visualizeLabel.setIcon(imgIcon);
                visualizeLabel.setHorizontalAlignment(JLabel.CENTER);
                visualizeLabel.setVerticalAlignment(JLabel.CENTER);
            }
        }
        setReportDate(false);
    }//GEN-LAST:event_changeViewCBoxItemChanged

    private void clearRecordDetails(){
        nameResultText.setText("");
        ageResultText.setText("");
        genderResultText.setText("");
        dateResultText.setText("");
        resultText.setText("--");
        descriptionText.setText("--");
        noOfChannelsDetailsText.setText("");
        durationDetailsText.setText("");
        recordedDateDetailsText.setText("");
        channelNamesDetailsText.setText("");
    }
    
    /**
     * Set visibility of the section inside result section of prediction tab
     * @param bool 
     */
    private void setVisibilityOfResultSection(boolean bool){
        resultHeaderLabel.setVisible(bool);
        resultSeperator.setVisible(bool);
        nameResultLabel.setVisible(bool);
        nameResultText.setVisible(bool);
        ageResultLabel.setVisible(bool);
        ageResultText.setVisible(bool);
        genderResultLabel.setVisible(bool);
        genderResultText.setVisible(bool);
        dateResultLabel.setVisible(bool);
        dateResultText.setVisible(bool);
        resultPanel.setVisible(bool);
        resultLabel.setVisible(bool);
        resultText.setVisible(bool);
        descriptionText.setVisible(bool);
        eegSignalDetailsLabel.setVisible(bool);
        noOfChannelsDetailsLabel.setVisible(bool);
        noOfChannelsDetailsText.setVisible(bool);
        durationDetailsLabel.setVisible(bool);
        durationDetailsText.setVisible(bool);
        recordedDateDetailsLabel.setVisible(bool);
        recordedDateDetailsText.setVisible(bool);
        channelNamesDetailsLabel.setVisible(bool);
        channelNamesDetailsText.setVisible(bool);
    }
    
    /**
     * 
     */
    private void setToolIcons(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ASDGenus.png")));
        imageLabel.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("ASDGenus_logo.jpg")).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
    }
    
    /**
     *  
     * @return current date time in the format Sep 30, 2019 12:39:02PM
     */
    private void setReportDate(boolean needUpdate){
        String date;
        if(needUpdate){
            date = DateFormat.getDateTimeInstance().format(Calendar.getInstance().getTime());
            dateResultText.setText(date);
        }else{
            if(dateResultText.getText().equals("")){
            date = DateFormat.getDateTimeInstance().format(Calendar.getInstance().getTime());
            dateResultText.setText(date);
        }
        }
    }
    
    /**
     * to get the image with required fix size
     * @param imagePath
     * @return 
     */
    private ImageIcon getFitSizeImage(String imagePath){
        ImageIcon imgIcon;
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(1200, 600,Image.SCALE_SMOOTH);
        imgIcon = new ImageIcon(dimg);
        return imgIcon;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HelpPanel;
    private javax.swing.JPanel PredictPanel;
    private javax.swing.JPanel VisualizePanel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageResultLabel;
    private javax.swing.JLabel ageResultText;
    private javax.swing.JTextField ageText;
    private javax.swing.JLabel asdResultLabel;
    private javax.swing.JButton browseBtn;
    private javax.swing.JTextField browseTxt;
    private javax.swing.JComboBox<String> changeViewComboBox;
    private javax.swing.JLabel channelNamesDetailsLabel;
    private javax.swing.JLabel channelNamesDetailsText;
    private javax.swing.JLabel dateResultLabel;
    private javax.swing.JLabel dateResultText;
    private javax.swing.JLabel descriptionText;
    private javax.swing.JLabel durationDetailsLabel;
    private javax.swing.JLabel durationDetailsText;
    private javax.swing.JPanel eegImportOuterPanel;
    private javax.swing.JLabel eegSignalDetailsLabel;
    private javax.swing.ButtonGroup evaluateDataRButtonGroup;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderResultLabel;
    private javax.swing.JLabel genderResultText;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel importEEGHeadingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel mainPreditionResultPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameResultLabel;
    private javax.swing.JLabel nameResultText;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel noOfChannelsDetailsLabel;
    private javax.swing.JLabel noOfChannelsDetailsText;
    private javax.swing.JLabel pDetaiHeadinglLabel;
    private javax.swing.JPanel pDetailInnerLabel;
    private javax.swing.JPanel pDetailOuterPanel;
    private javax.swing.JButton predictASDButton;
    private javax.swing.JPanel predictionPanel;
    private javax.swing.JLabel recordedDateDetailsLabel;
    private javax.swing.JLabel recordedDateDetailsText;
    private javax.swing.JLabel resultHeaderLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JSeparator resultSeperator;
    private javax.swing.JLabel resultText;
    private javax.swing.JButton saveResultButton;
    private javax.swing.JLabel visualizeLabel;
    private javax.swing.JLabel visualizeNameLabel;
    // End of variables declaration//GEN-END:variables
}
